FROM node:20-alpine AS build
WORKDIR /app/frontend

COPY package*.json ./
RUN npm ci --prefer-offline --no-audit

COPY . ./
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/frontend/dist ./

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]