services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: noc-backend
    expose:
      - "8000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - TZ=Europe/Moscow
    restart: always
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: noc-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge