# Generated by Django 5.2.17 on 2026-09-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название локации')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Локация / Папка',
                'verbose_name_plural': 'Локации / Папки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(db_index=True, max_length=100, verbose_name='Идентификатор узла (IP или OLT:Port:ONU)')),
                ('device_type', models.CharField(choices=[('sw', 'Коммутатор L2'), ('olt', 'OLT Станция'), ('onu', 'Оптика GPON ONU')], default='sw', max_length=10, verbose_name='Тип устройства')),
                ('start_time', models.IntegerField(db_index=True, verbose_name='Время старта (UNIX)')),
                ('end_time', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Время восстановления (UNIX)')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (сек)')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'История инцидентов',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='OltDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('model_type', models.CharField(choices=[('c300', 'ZTE C300 / C320'), ('c600', 'ZTE C600 / C650')], default='c300', max_length=20, verbose_name='Тип станции')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Логин Telnet')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль Telnet')),
                ('port', models.PositiveIntegerField(default=23, verbose_name='Порт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опрашивать')),
            ],
            options={
                'verbose_name': 'OLT станция',
                'verbose_name_plural': 'OLT станции',
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP адрес')),
                ('description', models.CharField(max_length=255, verbose_name='Адрес / Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опрашивать')),
                ('model_override', models.CharField(blank=True, max_length=100, verbose_name='Модель (если не определена по SNMP)')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='inventory.cluster', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Коммутатор',
                'verbose_name_plural': 'Коммутаторы',
                'ordering': ['cluster', 'ip'],
            },
        ),
    ]
